# MySql

CREATE DATABASE IF NOT EXISTS forumnet;
USE forumnet

CREATE TABLE IF NOT EXISTS user(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    IDENTIFIER TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    ROLE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS forum(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CREATION_DATE DATETIME NOT NULL,
    OWNER VARCHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS forum_user(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    ASSOCIATED_USER VARCHAR(36) NOT NULL,
    FORUM VARCHAR(36) NOT NULL,
    DISPLAY_NAME TEXT NOT NULL,
    BIOGRAPHY TEXT NOT NULL,
    LINKS TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS post(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    FORUM VARCHAR(36) NOT NULL,
    TITLE TEXT NOT NULL,
    BODY TEXT NOT NULL,
    CATEGORY TEXT NOT NULL,
    AUTHOR_FORUM_USER VARCHAR(36) NOT NULL,
    CREATION_DATE DATETIME NOT NULL
);