# MySql

CREATE DATABASE maindb;

CREATE TABLE [IF NOT EXISTS] users (
    ID TEXT PRIMARY KEY NOT NULL,
    Identifier TEXT NOT NULL,
    Password TEXT NOT NULL,
    Role INT NOT NULL
);

CREATE TABLE [IF NOT EXISTS] forums(
    ID TEXT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CREATION_DATE DATETIME NOT NULL,
    CATEGORIES MMM NOT NULL,
    OWNER TEXT NOT NULL
);

CREATE TABLE [IF NOT EXISTS] forum_users(
    ID TEXT PRIMARY KEY NOT NULL,
    ASSOCIATED_USER_ID TEXT NOT NULL,
    FORUM_ID TEXT NOT NULL,
    DISPLAY_NAME TEXT NOT NULL,
    BIOGRAPHY TEXT NOT NULL,
    LINKS MMM NOT NULL,
);

CREATE TABLE [IF NOT EXISTS] categories(
    ID TEXT PRIMARY KEY NOT NULL
    POSTS MMM NOT NULL,
    CATEGORIES MMM NOT NULL
);

CREATE TABLE [IF NOT EXISTS] posts(
    ID TEXT PRIMARY KEY NOT NULL,
    TITLE TEXT NOT NULL,
    BODY TEXT NOT NULL,
    CATEGORY TEXT NOT NULL
    AUTHOR_FORUM_USER_ID TEXT FOREIGN KEY NOT NULL,
    CREATION_DATE DATETIME NOT NULL
);

CREATE TABLE [IF NOT EXISTS] post_assoc(
    POST_ID TEXT PRIMARY KEY NOT NULL
    FORUM_ID TEXT FORIEGN KEY NOT NULL
)